### ISSUE TITLE
[코드 리뷰] 5일차 클린 코드 리뷰

### ISSUE THREAD

**Issue by HyeongSeop-Kim** [SungbinYang/inflearn-study-club0#1]
1. 디자인 패턴의 적용
-  디자인 패턴을 적용하는 것도 좋지만 적용하기 전 꼭 필요한가도 고민해보면 좋을 것 같습니다. 저는 이전의 Dice 클래스로 충분한 리팩터링이 되었다고 생각이 되어서요! 이유는 다음과 같습니다.

  - 이미 주사위의 크기를 생성자를 통해 받고 있어 주사위 종류에 대한 확장성이 충분한 것으로 보인다.
  - 주사위를 굴리는 기능과 그 결과 값을 가져오는 기능이 다르게 구현될 가능성이 없어보인다.

그래도 디자인 패턴을 적용하는 시도는 너무 좋은 것 같습니다!

2. 예외 처리
- InputHandler에서의 예외 처리는 생각하지 못했는데 꼼꼼하신 것 같습니다.
- DiceRollHandler 에서 counts 배열을 초기화할 때 0 이 들어오면 ArrayIndexOutOfBoundsException이 발생할 수 있으나 주사위 면의 크기를 검증하는 부분이 다른 클래스에도 존재하지 않는 것 같습니다!

**Comment by SungbinYang** [comment]
아하! 형섭님 말씀처럼 디자인패텀을 적용하지 않더라도 생성자만으로 충분한 것 같네요! 의견 감사합니다!
예외처리에 대한 부분도 조언 감사드립니다!
